permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge
rdiscount:
  extensions: [smart]

paginate: 5
paginate_path: "page/:num"

tags_path: /tags.html
categories_path: /categories/html

production_url: http://blog.petergerritsen.nl

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Peter Gerritsen’s blog
tagline: about software development
author :
  name : Peter Gerritsen
  email : mail@petergerritsen.nl
  github : petergerritsen
  twitter : pjotr80
  linkedin : petergerritsen80
  feedburner : feedname
  
# Disqus  
disqus_short_name: petergerritsensblog
disqus_show_comment_count: true

# Google analytics
google_analytics_tracking_id: UA-19847311-1

# Github
github_repo_url: http://github.com/petergerritsen/blog.petergerritsen.nl/

