permalink: /:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true
markdown: redcarpet
rdiscount:
  extensions: [smart]

paginate: 5
paginate_path: "page/:num"

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Peter Gerritsen’s blog
tagline: about software development
author :
  name : Peter Gerritsen
  email : mail@petergerritsen.nl
  github : petergerritsen
  twitter : pjotr80
  linkedin : petergerritsen80
  feedburner : feedname
  
  
disqus_short_name: petergerritsensblog
google_analytics_tracking_id: UA-19847311-1

production_url: http://blog.petergerritsen.nl

github_repo_url: http://github.com/petergerritsen/blog.petergerritsen.nl/

